server:
  port: 8222

eureka:
  client:
    register-with-eureka: false

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: http://localhost:8092
          predicates:
            - Path=/api/**
        - id: user-service
          uri: http://localhost:8093
          predicates:
            - Path=/api/**