server:
  port: 8222

eureka:
  client:
    register-with-eureka: false

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: http://localhost:8092
          predicates:
            - Path=/api/v1/auth/**
        - id: user-service
          uri: http://localhost:8093
          predicates:
            - Path=/api/v1/user-detail/**
            - Path=/api/v1/company/**
        - id: education-service
          uri: http://localhost:8095
          predicates:
            - Path=/api/v1/education/**
        - id: user-education-service
          uri: http://localhost:8097
          predicates:
            - Path=/api/v2/user-detail/**
